/**
 * 路由表管理
 */
export class RoutePath {
  static readonly LoginPage = "pages/auth/LoginPage"
  static readonly WebPage = "pages/WebPage"
  static readonly SearchPage = "pages/search/SearchPage"
  static readonly RankPage = "pages/myself/rank/RankPage"
  static readonly CollectPage = "pages/myself/collect/CollectPage"
  static readonly MessagePage = "pages/myself/message/MessagePage"
  static readonly ProjectPage = "pages/myself/project/ProjectPage"
  static readonly SystemCategoryPage = "pages/myself/system/SystemCategoryPage"
  static readonly SystemPage = "pages/myself/system/SystemPage"
}